export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";
export const SEARCH_POSTS = "SEARCH_POSTS";
export const SEARCH_POSTS_SUCCESS = "SEARCH_POSTS_SUCCESS";
